  spring:
    data:
      mongodb:
        uri: mongodb://smartanswer:smartanswer@localhost:27017/smartanswer

  spring.jwt.secret: kimdonggeun12345kimdonggeun12345kimdonggeun12345kimdonggeun12345

  cloud:
    aws:
      credentials:
        accessKey: AKIAX64BLXE7TDSZXPGY
        secretKey: 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
      s3:
        bucket: pnuprojects
        folderName : static
      region:
        static: ap-northeast-2
      stack:
        auto: false